### ISSUE TITLE
Questions about the Hierarchical Constraint Enforcing Loss

### ISSUE THREAD

**Issue by suoych** [salesforce/hierarchicalContrastiveLearning#1]
Hi! Thanks for sharing your impressive work. I got some questions while reading the paper. I would be grateful if you can give some further explanation. 

1. The figure illustrates the label hierarchy. Do the brighter blue circles indicate the class higher in the hierarchy level as you mentioned in the next few sections?
![image](https://user-images.githubusercontent.com/29878050/167087641-d6b26859-d82c-46fb-99ab-7e758ab0d80c.png)

2. If so, what is the intuition of the hierarchical constraint enforcing loss? Why a class in the higher level should gain a higher confidence score? Common sense might be like that a picture of jeans should get a higher confidence score in a lower level class such as clothes instead of the higher class such as jeans. 

3.  Higher confidence means lower loss, then is the loss function reasonable? Is L the highest level and 0 the lowest level? The equation raises the loss value in lower level. Is that the opposite of what you claimed?
By the way, the paper says the loss is calculated in the descending order of L, which is the same in the code implementation. if so, the equation should be L(l+1) instead of L(l-1) since the max value of L(l-1) can not be acquired when you are calculating the L(l).
![image](https://user-images.githubusercontent.com/29878050/167090104-71eb6ae2-e1a5-43c6-b181-db311c909a09.png)

**Comment by shugerdou** [comment]
Thanks for your interests in this work. 
1. Different brightnesses represent different samples in the same hierarchy level. In Figure 1 in the paper, we state that "Different shades of blue nodes indicate their relationship to the anchor image, with darkness in shades of blue corresponding to increasing distance." In other words, the bright node is closer to the anchor image than the dark node, and they belong to the same level.
2. I guess that your misunderstanding is coming from an assumption that for the same image pair, we compare the score at different levels. This is different from our assumptions. We define the hierarchical constraint loss on pairs at the current level in comparison to the lower level pairs. Two images of the same product cannot have a lower confidence than two images of a different product but in the same category.
3. We thank that you find a typo. Yes, this should be $l+1$. We have clarified it in README.

**Comment by suoych** [comment]
> Thanks for your interests in this work.
> 
> 1. Different brightnesses represent different samples in the same hierarchy level. In Figure 1 in the paper, we state that "Different shades of blue nodes indicate their relationship to the anchor image, with darkness in shades of blue corresponding to increasing distance." In other words, the bright node is closer to the anchor image than the dark node, and they belong to the same level.
> 2. I guess that your misunderstanding is coming from an assumption that for the same image pair, we compare the score at different levels. This is different from our assumptions. We define the hierarchical constraint loss on pairs at the current level in comparison to the lower level pairs. Two images of the same product cannot have a lower confidence than two images of a different product but in the same category.
> 3. We thank that you find a typo. Yes, this should be $l+1$. We have clarified it in README.

Thanks a lot!
